export { default as Home } from './Home'
export{ default as Public } from './Public'
export{ default as Login } from './Login'
export{ default as Album } from './Album'
export{ default as ZingChart } from './ZingChart'
export{ default as Search } from './Search'
export{ default as SearchAll } from './SearchAll'
export{ default as SearchSong } from './SearchSong'
export{ default as Singer } from './Singer'
export{ default as SearchPlaylist } from './SearchPlaylist'
export{ default as WeekRankPage } from './WeekRankPage'
export{ default as Personal } from './Personal'
export{ default as Processing } from './Processing'